### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by rileyjshaw** [cdnjs/cdnjs-importer#1]
After running:

```
cdnjs-importer -c ~/code/cdnjs/ git@github.com:rileyjshaw/terra.git
```

I'm getting the error:

```
info  [21:49.31 - 12.04.2015] Clonning git@github.com:rileyjshaw/terra.git into /var/folders/45/< __redacted__ >
error [21:49.31 - 12.04.2015] Failed to clone the repository: Error: Command failed: Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any thoughts?

**Comment by IonicaBizau** [comment]
It seems that the SSH keys are not set up on your computer. Reffer to [this article](https://help.github.com/articles/generating-ssh-keys/) on how to generate the SSH keys on your machine.

However, the HTTPS protocol should work:

``` sh
cdnjs-importer -c $HOME/code/cdnjs https://github.com/rileyjshaw/terra.git
```

I see a little thing here that could be considered as bug: handling `~` as home directory. Most probably I will add the [`fs-plus`](https://github.com/atom/fs-plus) library to handle it.

Tell me if that worked for you and if you have other questions. :smile:

**Comment by rileyjshaw** [comment]
Ah - you're totally right. I'm used to using HTTPS, so I didn't realize that I hadn't set up my keys properly on this machine. Thanks for the quick response!

**Comment by IonicaBizau** [comment]
You're welcome! Glad to see that the _sweep_ creator uses this library. :smile: I saw that project some time ago and I really liked it. :+1:

**Comment by IonicaBizau** [comment]
Handling `~` should work in `1.2.0`. :ship: You can upgrade using `npm i -g cdnjs-importer@latest`.

**Comment by rileyjshaw** [comment]
Cool, thanks!!!
