### ISSUE TITLE
Support import from git repo

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs-importer#11]

**Comment by IonicaBizau** [comment]
Could you please detail what is this about? The importer already knows to clone the git repository and copy the needed files in the cdnjs directory.

**Comment by PeterDaveHello** [comment]
Oops, actually I meant support setup git auto-update!

**Comment by IonicaBizau** [comment]
@PeterDaveHello Currently it sets up the `npmUpdate`. How should it handle git auto-update?

**Comment by PeterDaveHello** [comment]
We use the tags in git repo to recognize the versions, a sample config:
https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update

**Comment by IonicaBizau** [comment]
@PeterDaveHello Got it. So, if `autoupdate` is there, then [this step will be skipped](https://github.com/IonicaBizau/cdnjs-importer/blob/6836f6f378802c0d1d950d6a5064f28bd42db534/lib/index.js#L183-L190). Am I correct?

**Comment by PeterDaveHello** [comment]
Yes, it should be skipped!

**Comment by IonicaBizau** [comment]
:+1: I'm on it. Probably today or tomorrow will release the new version of this tool.

**Comment by PeterDaveHello** [comment]
:+1:
