### ISSUE TITLE
Testing without cdnjs repo

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs-importer#16]

**Comment by IonicaBizau** [comment]
What is this about?

**Comment by PeterDaveHello** [comment]
> peter@peter-lab /run/shm/cdnjs-importer $ npm test
> 
> > cdnjs-importer@1.4.1 test /run/shm/cdnjs-importer
> > node test
> 
> [Error: The cdnjs library directory doesn't exist.]

**Comment by PeterDaveHello** [comment]
Hope we can run the test without cdnjs repo, or you wanna run `npm test` in cdnjs's main repo after added a lib?

**Comment by IonicaBizau** [comment]
@PeterDaveHello That _test_ is actually an example. :laughing:

**Comment by PeterDaveHello** [comment]
hmmmm ... okay, I thought it was unit testing :smile:
